 ceci  ~  Prodabel  sandbox  poc-dom  1  time python3 main.py input/ --no-clear > out9
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
^CTraceback (most recent call last):
  File "main.py", line 29, in <module>
    convertFile(input_dir+filename, clear)
  File "main.py", line 8, in convertFile
    parseFiles(lines, num_edicao, clear)
  File "/mnt/dados/sandbox/poc-dom/parser.py", line 174, in parseFiles
    convertAllAnexosToPDF(id, num_edicao)
  File "/mnt/dados/sandbox/poc-dom/parser.py", line 105, in convertAllAnexosToPDF
    convertToPDF(input_dir+'/'+filename, output_dir)
  File "/mnt/dados/sandbox/poc-dom/parser.py", line 92, in convertToPDF
    subprocess.run(["lowriter", "--headless", "--convert-to", "pdf", "--outdir", output_path, file_path])
  File "/usr/lib/python3.8/subprocess.py", line 491, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1016, in communicate
    self.wait()
  File "/usr/lib/python3.8/subprocess.py", line 1079, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1804, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.8/subprocess.py", line 1762, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt

real    381m41,165s
user    61m19,318s
sys     71m26,158s
